---
- name: Fail when alloy_config is empty
  ansible.builtin.fail:
    msg: Variable alloy_config is required!
  when: alloy_config | length < 1

- name: Extract IP address and PORT from alloy_env_file_vars
  when: alloy_env_file_vars.CUSTOM_ARGS is defined and alloy_env_file_vars.CUSTOM_ARGS | length > 0
  block:
    - name: Search for server.http.listen-addr string
      set_fact:
        __alloy_server_http_listen_addr_regex: "{{ alloy_env_file_vars.CUSTOM_ARGS | regex_search('--server.http.listen-addr=([\\d\\.]+):(\\d+)') }}"

    - name: Extract IP address and port
      set_fact:
        __alloy_server_http_listen_address: "{{ __alloy_server_http_listen_addr_regex | regex_search('(?<!:)(\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b)(?=:)') }}"
        __alloy_server_http_listen_port: "{{ __alloy_server_http_listen_addr_regex | regex_search('(?<=:)(\\d+)$') }}"
      when: __alloy_server_http_listen_addr_regex | length > 0

    - name: Assert that extracted IP address is valid
      ansible.builtin.assert:
        that: __alloy_server_http_listen_address | ansible.utils.ipaddr
      when: __alloy_server_http_listen_addr_regex | length > 0
