---
- name: ZYPPER - Install Alloy from remote URL
  ansible.builtin.zypper:
    name: "{{ alloy_download_url_rpm }}"
    state: present
    disable_gpg_check: true
  notify: restart alloy
  when: (__current_deployed_version.stdout is not defined or alloy_version not in __current_deployed_version.stdout) and alloy_install_type == "url"

- name: Install required packages for repository installation
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ __alloy_required_packages }}"
  when: alloy_install_type == "repository"

- name: Import grafana signing key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ alloy_rpm_signing_key_url }}"
  when: alloy_install_type == "repository"

- name: Add grafana zypper repository
  community.general.zypper_repository:
    name: grafana
    repo: "{{ alloy_rpm_repo_url }}"
    state: present
  when: alloy_install_type == "repository"

- name: ZYPPER - Install Alloy from Repository
  community.general.zypper:
    name: alloy
    state: present
    update_cache: true
