- name: test
  hosts: localhost

  tasks:
    - name: Create/Update a dashboard
      grafana.grafana.dashboard:
        dashboard: {
          "dashboard": {
            "id": null,
            "uid": test123,
            "title": "Production Overview",
            "tags": [ "templated" ],
            "timezone": "browser",
            "schemaVersion": 16,
            "version": 0,
            "refresh": "25s"
          },
          "overwrite": true
        }
        stack_slug: ansibletest
        grafana_api_key: eyJrIjoiOElWQmdLd0R5c1FWVVJKd0g3bFNNdm1mak83QjgwSEQiLCJuIjoiQW5zaWJsZS1HaXRodWItQWN0aW9uIiwiaWQiOjF9
        state: present