- name: Restart alloy
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: restarted
  become: true
  listen: "Restart alloy"
  when: not ansible_check_mode

- name: Check alloy is started properly
  ansible.builtin.include_tasks: ga-started.yml
  listen: "Restart alloy"
