---
name: Grafana Agent Role

on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:

  linux:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    runs-on: ubuntu-20.04
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install ansible-base (stable-2.14)
        run: pip install https://github.com/ansible/ansible/archive/stable-2.14.tar.gz --disable-pip-version-check

      - name: Run Grafana Agent Role test
        run: ansible-playbook tests/integration/targets/grafana_agent/linux.yml